- name: Add Application user
  user:
    name: "{{ APP_USER }}"

- name: Install Java
  yum:
    name: java
    state: present

- name: Download Azure Artifacts
  include_role:
    name: common
    tasks_from: azure-artifacts
  vars:
    ARTIFACT_PATH: /home/{{APP_USER}}/{{component}}
    COMPONENT: shipping
    COMPONENT_ID: 600993d5-e4c8-4ec2-a8ce-9df2f2c2950c
    type: application

- name: Setup SystemD Service for Shipping
  template:
    src: systemd.service
    dest: /etc/systemd/system/shipping.service

- name: Start User Service
  systemd:
    name: shipping
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Install Prometheus
  include_role:
    name: prometheus

- name: Install Filebeat
  include_role:
    name: filebeat
  vars:
    APP_NAME: shipping
