- name: Demo on filters
  hosts: localhost
  vars:
    URL: https://github.com/prometheus/prometheus/releases/download/v2.22.2/prometheus-2.22.2.linux-amd64.tar.gz
  tasks:
    - name: print
      debug:
        msg: "{{URL.split('/') | last | replace('.tar.gz', '')}}"
