- name: Install NodeJS
  yum:
    name: nodejs
    state: present

- name: Add Application user
  user:
    name: "{{ APP_USER }}"

- name: Download Azure Artifacts
  include_role:
    name: common
    tasks_from: azure-artifacts
  vars:
    ARTIFACT_PATH: /home/{{APP_USER}}/{{component}}
    COMPONENT: user
    COMPONENT_ID: ddbd08f1-1f22-4a14-a577-87e77168086b
    type: application

- name: Setup SystemD Service for User
  template:
    src: systemd.service
    dest: /etc/systemd/system/user.service

- name: Start User Service
  systemd:
    name: user
    state: restarted
    enabled: yes

- name: Install Prometheus
  include_role:
    name: prometheus

- name: Install Filebeat
  include_role:
    name: filebeat
  vars:
    APP_NAME: user
