- name: Install ErLang
  yum:
    name: https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_22.2.1-1~centos~7_amd64.rpm
    state: present

- name: Setup Yum repos
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install RabbitMQ Server
  yum:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Create roboshop app user
  shell: rabbitmqctl add_user roboshop roboshop123; rabbitmqctl set_user_tags roboshop administrator; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

## Hardcoded the passwords, need to change them.
- name: Install Prometheus
  include_role:
    name: prometheus
