- name: Install NodeJS
  yum:
    name: nodejs
    state: present

- name: Add Application user
  user:
    name: "{{ APP_USER }}"

- name: Download Azure Artifacts
  include_role:
    name: common
    tasks_from: azure-artifacts
  vars:
    ARTIFACT_PATH: /home/{{APP_USER}}/{{component}}
    COMPONENT: catalogue
    COMPONENT_ID: 68a9d82d-836d-47cd-bf3e-89bd984aa3e6
    type: application

- name: Setup SystemD Service for Catalogue
  template:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Start Catalogue Service
  systemd:
    name: catalogue
    state: restarted
    enabled: yes

- name: Install Prometheus
  include_role:
    name: prometheus

- name: Install Filebeat
  include_role:
    name: filebeat
  vars:
    APP_NAME: catalogue

